### ISSUE TITLE
Feature Request: list required dependencies

### ISSUE THREAD

**Issue by SenorAgosto** [qbit/openbsd.app#1]
I would love if the site would not only find the packages, but after they've been found could list all the dependencies that need to be installed to install the package.

**Comment by rwp0** [comment]
Can create a `.cpanfile` otherwise do something like `grep -E 'use|require' openbsd.app.pl` I think

**Comment by qbit** [comment]
@rwp0 I assumed @SenorAgosto was talking about a searched package's dependencies. Probably would be a good to create a cpanfile anyway though :D

**Comment by SenorAgosto** [comment]
@qbit @rwp0 right, after finding a package using search, I'd like to see the dependencies needed to install the package. E.g. on the command line I would probably run something like `pkg_add -n <pkg>` and make a note of all the packages printed in the output. 

`pkg_add` reads the information from the `+CONTENTS` file IIRC. Which expresses dependencies using entries like `@depend` and `@wantlib`. I'd be most interested in the `@depend` entries b/c I think those are always packages.

**Comment by qbit** [comment]
![image](https://user-images.githubusercontent.com/68368/194446926-ee65c9d9-814d-4155-a3f1-d3633938d20a.png)

I have it mostly working (as far as a list of deps goes). 

I wasn't sure about adding it as a feature.. but I also wasn't sure how I could get a list of the deps (and I don't know of any other tools that do it currently).. But now I have the SQL to do it, so I might as well add the feature :D

Here is the SQL you can use to query `sqlports`:

``` SQL
  WITH RECURSIVE  
  under_port(name,level) AS (  
    VALUES(? ,0)  
    UNION ALL  
    SELECT _depends.fulldepends, under_port.level+1  
      FROM  
        _depends  
      JOIN _paths ON _paths.id=_depends.fullpkgpath  
      join under_port ON _paths.fullpkgpath = under_port.name  
      where  
        _depends.type IN (0, 1)  
     ORDER BY 2 DESC  
  )  
SELECT substr('..........',1,level*3) || name FROM under_port;  
```

**Comment by SenorAgosto** [comment]
@qbit dude, you rock! 

I should probably give you some context about why I would find this feature useful. 

I maintain some air gaped machines and have a list of packages I install with Ansible when doing upgrades, but they are top-level package names only. I'd hoped to get around to doing something like openbsd.app myself one day, but it never happened =) 

After each release of OBSD, I spend a lot of time grabbing packages, and then circling back to get dependencies, rinse and repeat. After maybe 6 or 7 cycles of that I can actually install all the packages I want. So, it's a huge pain in my arse. 

If you do end up adding this feature, I'm definitely hitting the support heart and tipping you a few hundred. :+1:

**Comment by qbit** [comment]
heh, right on, thanks :) 

You might want to look at `PKG_CACHE` in [pkg_add](https://man.openbsd.org/pkg_add)'s man page. If it's set it to a directory name `pkg_add` will send all the packages there (deps included), you can combine it with the `-n` flag to just fetch (no install). This would save ya a lot of time probably :D

**Comment by SenorAgosto** [comment]
I am aware of and use `PKG_CACHE` and `-n` extensively - how'd you think I was getting this packages :P

I don't grab packages from a bare bones install, and I originally thought it silently skipped anything that was installed on the local machine, but I just discovered `pkg_add -n -vv` _will_ print the already installed packages/dependencies. So that will definitely be helpful for my scenario. +1 for the man pages.

**Comment by qbit** [comment]
> how'd you think I was getting these packages :P

Your description made it sound like you were manually fetching them.

Anyway - you can use [proot](https://man.openbsd.org/proot) to do a "clean room" fetch of things. That way your current system packages won't get caught up in the mix.

**Comment by qbit** [comment]
Anyway: 

https://openbsd.app/tree?name=editors/neovim
and 
https://openbsd.app/tree?name=editors/neovim&raw=true
