### ISSUE TITLE
duplicity description seems broken (faulty escaping?)

### ISSUE THREAD

**Issue by ainar-g** [qbit/openbsd.app#2]
<https://openbsd.app/?search=duplicity>

The list “Other options are:” is formatted with \<h1\> for some reason:

![Screenshot 2023-06-28 at 11-03-42 OpenBSD app](https://github.com/qbit/openbsd.app/assets/4964986/1e789252-571e-4fac-8bb2-a774911f17cc)

**Comment by qbit** [comment]
I am parsing the DESCR contents as markdown to show the search highlights. Unfortunately some stuff uses non-markdown-ish: https://github.com/openbsd/ports/blob/master/sysutils/duplicity/pkg/DESCR#L18

I was planning on looking for other markdown parsers that let me do a bit more configuration - just hasn't been a priority.

**Comment by qbit** [comment]
Pushed a fix that just uses simple regex instead of full markdown parsing.
