### ISSUE TITLE
Bolding search results

### ISSUE THREAD

**Issue by bentley** [qbit/openbsd.app#4]
When searching for [`irssi`](https://openbsd.app/?search=irssi), the `irssi-xmpp` result is bolded incorrectly:

> **irssi\*\*-xmpp is an \*\*irssi** plugin to connect to the Jabber network.

Rather than:

> **irssi**-xmpp is an **irssi** plugin to connect to the Jabber network.

**Comment by qbit** [comment]
mmm, my regex is a bit clunky it seems.

**Comment by qbit** [comment]
https://openbsd.app/?search=irssi seems better now :D
