### ISSUE TITLE
grake's homepage leads to current openbsd.app page

### ISSUE THREAD

**Issue by Veraellyunjie** [qbit/openbsd.app#7]
Open
https://openbsd.app/?search=links
link of grake's "Home page" is
https://openbsd.app/?search=links

Open
https://openbsd.app/?search=youtube
link of grake's "Home page" is
https://openbsd.app/?search=youtube

Open
https://openbsd.app/?search=grake
link of grake's "Home page" is
https://openbsd.app/?search=grake

Coz href of grake's "Home page" is empty
```
                <li>
                    <a
                      href=""
                      title="Home page for grake-0.1.0p1"
                    >Home page</a>
                </li>
```

**Comment by qbit** [comment]
Thanks for reporting!
